env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
changelog:
  skip: true
brews:
  - name: parade
    tap:
      owner: chroju
      name: homebrew-tap
      token:
    url_template: "https://github.com/chroju/parade/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    description: "Parade is a simple CLI tool for AWS SSM parameter store."
    homepage: "https://github.com/chroju/parade"
    license: "MIT"
    test: |
      system "#{bin}/parade --version"
    install: |
      bin.install "parade"
